#compute GB for the ideal generated by x^3*y-z,x^2+z and x+y+z.

P.<x,y,z>=PolynomialRing(QQ)
I = P.ideal([x^3*y-z,x^2+z,x+y+z])
gb=I.groebner_basis()
#[y*z^2 + y*z + z^2, z^3 - y*z + z, y^2 + 2*y*z + z^2 + z, x + y + z]
Ideal(gb).basis_is_groebner()
#True
